name: mobile_dapp
description: A mobile dApp for blockchain interactions
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  hex: ^0.2.0
  http: ^1.3.0
  intl: ^0.20.2
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  web3dart: ^2.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
